#!/usr/bin/env bash
# tasks/prepare.sh
# Prepare workspace for a specific vendor
# Usage: VENDOR_ENABLED=VENDOR1 ./tasks/prepare.sh
# or: export VENDOR_ENABLED=VENDOR1 && ./tasks/prepare.sh

set -euo pipefail

# resolve script dir and project root (works with symlinks)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$PROJECT_ROOT"

# Where vendor configs live
VENDOR_CONFIG_DIR="config"

# public dir in project
PUBLIC_DIR="public"

# tsconfig paths filename in project and vendor's file name
TSCONFIG_TARGET="tsconfig.paths.json"

# Ensure VENDOR_ENABLED is set
if [ -z "${VENDOR_ENABLED-}" ]; then
  echo "ERROR: VENDOR_ENABLED is not set. Example: VENDOR_ENABLED=VENDOR1 ./tasks/prepare.sh"
  exit 2
fi

# Normalize vendor token (no trailing slashes, uppercase kept)
VENDOR="$VENDOR_ENABLED"
VENDOR_DIR="$VENDOR_CONFIG_DIR/${VENDOR}"   # lowercase folder name (if you use lowercase folders)
# If you keep vendor folders uppercase, use: VENDOR_DIR="$VENDOR_CONFIG_DIR/$VENDOR"

# If your config folders are named vendor1/vendor2 (lowercase),
# the line above converts VENDOR to lowercase. If yours are uppercase,
# change to the commented line.

if [ ! -d "$VENDOR_DIR" ]; then
  echo "ERROR: Vendor config directory not found: $VENDOR_DIR"
  echo "Available vendors:"
  if [ -d "$VENDOR_CONFIG_DIR" ]; then
    for d in "$VENDOR_CONFIG_DIR"/*; do
      [ -d "$d" ] && basename "$d"
    done
  fi
  exit 3
fi

echo "Preparing project for vendor: $VENDOR"
echo "Vendor config dir: $VENDOR_DIR"

# 1) Sync public assets
if [ -d "$VENDOR_DIR/public" ]; then
  echo "Syncing public/ from $VENDOR_DIR/public -> $PUBLIC_DIR/"
  # Create target dir if missing
  mkdir -p "$PUBLIC_DIR"
  # Use rsync so deletions in vendor/public will be mirrored; change flags as needed
  rsync -a --delete --exclude='.gitkeep' "$VENDOR_DIR/public/" "$PUBLIC_DIR/"
else
  echo "No vendor public/ directory found at: $VENDOR_DIR/public (skipping)"
fi

# 2) Copy tsconfig.paths.json if provided
if [ -f "$VENDOR_DIR/$TSCONFIG_TARGET" ]; then
  if [ -f "$TSCONFIG_TARGET" ]; then
    echo "Backing up existing $TSCONFIG_TARGET -> ${TSCONFIG_TARGET}.bak"
    cp -f "$TSCONFIG_TARGET" "${TSCONFIG_TARGET}.bak"
  fi
  echo "Copying $VENDOR_DIR/$TSCONFIG_TARGET -> $TSCONFIG_TARGET"
  cp -f "$VENDOR_DIR/$TSCONFIG_TARGET" "$TSCONFIG_TARGET"
else
  echo "No $TSCONFIG_TARGET in $VENDOR_DIR (skipping)"
fi

# 3) Create or overwrite .env.local for Vite to pick up vendor at dev-time
# Vite only exposes env vars prefixed with VITE_ to client code.
ENV_FILE=".env.local"
echo "Writing $ENV_FILE with VITE_VENDOR=$VENDOR"
cat > "$ENV_FILE" <<EOF
# Auto-generated by tasks/prepare.sh
VITE_VENDOR=$VENDOR
EOF

# 4) Optional: copy other files (favicon, theme, etc.) if present in vendor dir
# Example: copy vendor index.html partials if your setup uses them
if [ -d "$VENDOR_DIR/overrides" ]; then
  echo "Copying overrides from $VENDOR_DIR/overrides"
  rsync -a "$VENDOR_DIR/overrides/" .
fi

# copy vendor index.html into project root
if [ -f "$VENDOR_DIR/index.html" ]; then
  echo "Copying $VENDOR_DIR/index.html -> $PROJECT_ROOT/index.html"
  cp -f "$VENDOR_DIR/index.html" "$PROJECT_ROOT/index.html"
else
  echo "No vendor index.html found at: $VENDOR_DIR/index.html"
fi

echo "Prepare complete for $VENDOR"
exit 0
